//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IPSSER_PORTALEntities : DbContext
    {
        public IPSSER_PORTALEntities()
            : base("name=IPSSER_PORTALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_PORTAL_BIBLIOTECA_IMAGENES> TBL_PORTAL_BIBLIOTECA_IMAGENES { get; set; }
        public virtual DbSet<TBL_PORTAL_CATEGORIA_BIBLIOTECA_IMAGENES> TBL_PORTAL_CATEGORIA_BIBLIOTECA_IMAGENES { get; set; }
        public virtual DbSet<TBL_PORTAL_FRONT> TBL_PORTAL_FRONT { get; set; }
        public virtual DbSet<TBL_PORTAL_MODULO> TBL_PORTAL_MODULO { get; set; }
        public virtual DbSet<TBL_PORTAL_SLIDE> TBL_PORTAL_SLIDE { get; set; }
        public virtual DbSet<TBL_PORTAL_DIRECTORIO_INTERNO> TBL_PORTAL_DIRECTORIO_INTERNO { get; set; }
        public virtual DbSet<TBL_PORTAL_TRABAJA_CON_NOSOTROS> TBL_PORTAL_TRABAJA_CON_NOSOTROS { get; set; }
        public virtual DbSet<TBL_PORTAL_CONTENIDO> TBL_PORTAL_CONTENIDO { get; set; }
        public virtual DbSet<TBL_PORTAL_ROL> TBL_PORTAL_ROL { get; set; }
        public virtual DbSet<TBL_PORTAL_USUARIO> TBL_PORTAL_USUARIO { get; set; }
        public virtual DbSet<TBL_PORTAL_USUARIO_ROL> TBL_PORTAL_USUARIO_ROL { get; set; }
        public virtual DbSet<TBL_PORTAL_DOCUMENTO> TBL_PORTAL_DOCUMENTO { get; set; }
        public virtual DbSet<TBL_PORTAL_GALERIA> TBL_PORTAL_GALERIA { get; set; }
    
        public virtual int PA_DELETE_TBL_PORTAL_BIBLIOTECA_IMAGENES(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_BIBLIOTECA_IMAGENES", idImagenParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_CONTENIDO_IMAGENES(Nullable<int> idContenidoImagen)
        {
            var idContenidoImagenParameter = idContenidoImagen.HasValue ?
                new ObjectParameter("IdContenidoImagen", idContenidoImagen) :
                new ObjectParameter("IdContenidoImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_CONTENIDO_IMAGENES", idContenidoImagenParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_CONTENIDOFRONT(Nullable<int> idContenidoFront)
        {
            var idContenidoFrontParameter = idContenidoFront.HasValue ?
                new ObjectParameter("IdContenidoFront", idContenidoFront) :
                new ObjectParameter("IdContenidoFront", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_CONTENIDOFRONT", idContenidoFrontParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_CONTENIDOSLIDE(Nullable<int> idContenidoSlide)
        {
            var idContenidoSlideParameter = idContenidoSlide.HasValue ?
                new ObjectParameter("IdContenidoSlide", idContenidoSlide) :
                new ObjectParameter("IdContenidoSlide", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_CONTENIDOSLIDE", idContenidoSlideParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_FRONT(Nullable<int> idFront)
        {
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_FRONT", idFrontParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_FRONT_IMAGENES(Nullable<int> idFrontImagenes)
        {
            var idFrontImagenesParameter = idFrontImagenes.HasValue ?
                new ObjectParameter("IdFrontImagenes", idFrontImagenes) :
                new ObjectParameter("IdFrontImagenes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_FRONT_IMAGENES", idFrontImagenesParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_SLIDE(Nullable<int> idSlide)
        {
            var idSlideParameter = idSlide.HasValue ?
                new ObjectParameter("IdSlide", idSlide) :
                new ObjectParameter("IdSlide", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_SLIDE", idSlideParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_BIBLIOTECA_IMAGENES(string titulo, string descripcion, string path)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_BIBLIOTECA_IMAGENES", tituloParameter, descripcionParameter, pathParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_CONTENIDO_IMAGENES(Nullable<int> idContenido, Nullable<int> idImagen)
        {
            var idContenidoParameter = idContenido.HasValue ?
                new ObjectParameter("IdContenido", idContenido) :
                new ObjectParameter("IdContenido", typeof(int));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_CONTENIDO_IMAGENES", idContenidoParameter, idImagenParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_CONTENIDOFRONT(Nullable<int> idFront, string titulo, string descripcion, string contenido_Uno, string contenido_Dos, string contenido_Tres, Nullable<int> idImagen, string link)
        {
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var contenido_UnoParameter = contenido_Uno != null ?
                new ObjectParameter("Contenido_Uno", contenido_Uno) :
                new ObjectParameter("Contenido_Uno", typeof(string));
    
            var contenido_DosParameter = contenido_Dos != null ?
                new ObjectParameter("Contenido_Dos", contenido_Dos) :
                new ObjectParameter("Contenido_Dos", typeof(string));
    
            var contenido_TresParameter = contenido_Tres != null ?
                new ObjectParameter("Contenido_Tres", contenido_Tres) :
                new ObjectParameter("Contenido_Tres", typeof(string));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var linkParameter = link != null ?
                new ObjectParameter("Link", link) :
                new ObjectParameter("Link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_CONTENIDOFRONT", idFrontParameter, tituloParameter, descripcionParameter, contenido_UnoParameter, contenido_DosParameter, contenido_TresParameter, idImagenParameter, linkParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_CONTENIDOSLIDE(Nullable<int> idSlide, string titulo, string descripcion, string contenido_Uno, string contenido_Dos, string contenido_Tres, Nullable<int> idImagen, string link)
        {
            var idSlideParameter = idSlide.HasValue ?
                new ObjectParameter("IdSlide", idSlide) :
                new ObjectParameter("IdSlide", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var contenido_UnoParameter = contenido_Uno != null ?
                new ObjectParameter("Contenido_Uno", contenido_Uno) :
                new ObjectParameter("Contenido_Uno", typeof(string));
    
            var contenido_DosParameter = contenido_Dos != null ?
                new ObjectParameter("Contenido_Dos", contenido_Dos) :
                new ObjectParameter("Contenido_Dos", typeof(string));
    
            var contenido_TresParameter = contenido_Tres != null ?
                new ObjectParameter("Contenido_Tres", contenido_Tres) :
                new ObjectParameter("Contenido_Tres", typeof(string));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var linkParameter = link != null ?
                new ObjectParameter("Link", link) :
                new ObjectParameter("Link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_CONTENIDOSLIDE", idSlideParameter, tituloParameter, descripcionParameter, contenido_UnoParameter, contenido_DosParameter, contenido_TresParameter, idImagenParameter, linkParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_FRONT(Nullable<int> idModulo, string titulo, string descripcion, Nullable<int> idImagen)
        {
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_FRONT", idModuloParameter, tituloParameter, descripcionParameter, idImagenParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_FRONT_IMAGENES(Nullable<int> idFront, Nullable<int> idImagen)
        {
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_FRONT_IMAGENES", idFrontParameter, idImagenParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_SLIDE(Nullable<int> idFront, Nullable<int> idImagen, string titulo, string descripcion, string contenido_Uno, string contenido_Dos, string contenido_Tres, string link)
        {
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var contenido_UnoParameter = contenido_Uno != null ?
                new ObjectParameter("Contenido_Uno", contenido_Uno) :
                new ObjectParameter("Contenido_Uno", typeof(string));
    
            var contenido_DosParameter = contenido_Dos != null ?
                new ObjectParameter("Contenido_Dos", contenido_Dos) :
                new ObjectParameter("Contenido_Dos", typeof(string));
    
            var contenido_TresParameter = contenido_Tres != null ?
                new ObjectParameter("Contenido_Tres", contenido_Tres) :
                new ObjectParameter("Contenido_Tres", typeof(string));
    
            var linkParameter = link != null ?
                new ObjectParameter("Link", link) :
                new ObjectParameter("Link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_SLIDE", idFrontParameter, idImagenParameter, tituloParameter, descripcionParameter, contenido_UnoParameter, contenido_DosParameter, contenido_TresParameter, linkParameter);
        }
    
        public virtual ObjectResult<PA_SELECT_FRONTS_Result> PA_SELECT_FRONTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_FRONTS_Result>("PA_SELECT_FRONTS");
        }
    
        public virtual ObjectResult<PA_SELECT_FRONTS_CON_SLIDES_Result> PA_SELECT_FRONTS_CON_SLIDES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_FRONTS_CON_SLIDES_Result>("PA_SELECT_FRONTS_CON_SLIDES");
        }
    
        public virtual ObjectResult<PA_SELECT_FRONTS_CON_SLIDESXIDMODULO_Result> PA_SELECT_FRONTS_CON_SLIDESXIDMODULO(Nullable<int> idModulo)
        {
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_FRONTS_CON_SLIDESXIDMODULO_Result>("PA_SELECT_FRONTS_CON_SLIDESXIDMODULO", idModuloParameter);
        }
    
        public virtual int PA_SELECT_FRONTSXIDMODULO(Nullable<int> idModulo)
        {
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_FRONTSXIDMODULO", idModuloParameter);
        }
    
        public virtual ObjectResult<PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENES_Result> PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENES_Result>("PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENES");
        }
    
        public virtual ObjectResult<PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENESXID_Result> PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENESXID(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENESXID_Result>("PA_SELECT_TBL_PORTAL_BIBLIOTECA_IMAGENESXID", idImagenParameter);
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_CONTENIDO_IMAGENES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_CONTENIDO_IMAGENES");
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_CONTENIDO_IMAGENESXID(Nullable<int> idContenidoImagen)
        {
            var idContenidoImagenParameter = idContenidoImagen.HasValue ?
                new ObjectParameter("IdContenidoImagen", idContenidoImagen) :
                new ObjectParameter("IdContenidoImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_CONTENIDO_IMAGENESXID", idContenidoImagenParameter);
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_CONTENIDOFRONT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_CONTENIDOFRONT");
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_CONTENIDOFRONTXID(Nullable<int> idContenidoFront)
        {
            var idContenidoFrontParameter = idContenidoFront.HasValue ?
                new ObjectParameter("IdContenidoFront", idContenidoFront) :
                new ObjectParameter("IdContenidoFront", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_CONTENIDOFRONTXID", idContenidoFrontParameter);
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_CONTENIDOSLIDE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_CONTENIDOSLIDE");
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_CONTENIDOSLIDEXID(Nullable<int> idContenidoSlide)
        {
            var idContenidoSlideParameter = idContenidoSlide.HasValue ?
                new ObjectParameter("IdContenidoSlide", idContenidoSlide) :
                new ObjectParameter("IdContenidoSlide", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_CONTENIDOSLIDEXID", idContenidoSlideParameter);
        }
    
        public virtual ObjectResult<PA_SELECT_TBL_PORTAL_FRONT_Result> PA_SELECT_TBL_PORTAL_FRONT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_TBL_PORTAL_FRONT_Result>("PA_SELECT_TBL_PORTAL_FRONT");
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_FRONT_IMAGENES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_FRONT_IMAGENES");
        }
    
        public virtual int PA_SELECT_TBL_PORTAL_FRONT_IMAGENESXID(Nullable<int> idFrontImagenes)
        {
            var idFrontImagenesParameter = idFrontImagenes.HasValue ?
                new ObjectParameter("IdFrontImagenes", idFrontImagenes) :
                new ObjectParameter("IdFrontImagenes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_SELECT_TBL_PORTAL_FRONT_IMAGENESXID", idFrontImagenesParameter);
        }
    
        public virtual ObjectResult<PA_SELECT_TBL_PORTAL_FRONTXID_Result> PA_SELECT_TBL_PORTAL_FRONTXID(Nullable<int> idFront)
        {
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_TBL_PORTAL_FRONTXID_Result>("PA_SELECT_TBL_PORTAL_FRONTXID", idFrontParameter);
        }
    
        public virtual ObjectResult<PA_SELECT_TBL_PORTAL_MODULO_Result> PA_SELECT_TBL_PORTAL_MODULO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_TBL_PORTAL_MODULO_Result>("PA_SELECT_TBL_PORTAL_MODULO");
        }
    
        public virtual ObjectResult<PA_SELECT_TBL_PORTAL_SLIDE_Result> PA_SELECT_TBL_PORTAL_SLIDE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_TBL_PORTAL_SLIDE_Result>("PA_SELECT_TBL_PORTAL_SLIDE");
        }
    
        public virtual ObjectResult<PA_SELECT_TBL_PORTAL_SLIDEXID_Result> PA_SELECT_TBL_PORTAL_SLIDEXID(Nullable<int> idSlide)
        {
            var idSlideParameter = idSlide.HasValue ?
                new ObjectParameter("IdSlide", idSlide) :
                new ObjectParameter("IdSlide", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_SELECT_TBL_PORTAL_SLIDEXID_Result>("PA_SELECT_TBL_PORTAL_SLIDEXID", idSlideParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_BIBLIOTECA_IMAGENES(Nullable<int> idImagen, string titulo, string descripcion, string path)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_BIBLIOTECA_IMAGENES", idImagenParameter, tituloParameter, descripcionParameter, pathParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_CONTENIDO_IMAGENES(Nullable<int> idContenidoImagen, Nullable<int> idContenido, Nullable<int> idImagen)
        {
            var idContenidoImagenParameter = idContenidoImagen.HasValue ?
                new ObjectParameter("IdContenidoImagen", idContenidoImagen) :
                new ObjectParameter("IdContenidoImagen", typeof(int));
    
            var idContenidoParameter = idContenido.HasValue ?
                new ObjectParameter("IdContenido", idContenido) :
                new ObjectParameter("IdContenido", typeof(int));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_CONTENIDO_IMAGENES", idContenidoImagenParameter, idContenidoParameter, idImagenParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_CONTENIDOFRONT(Nullable<int> idContenidoFront, Nullable<int> idFront, string titulo, string descripcion, string contenido_Uno, string contenido_Dos, string contenido_Tres, Nullable<int> idImagen, string link)
        {
            var idContenidoFrontParameter = idContenidoFront.HasValue ?
                new ObjectParameter("IdContenidoFront", idContenidoFront) :
                new ObjectParameter("IdContenidoFront", typeof(int));
    
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var contenido_UnoParameter = contenido_Uno != null ?
                new ObjectParameter("Contenido_Uno", contenido_Uno) :
                new ObjectParameter("Contenido_Uno", typeof(string));
    
            var contenido_DosParameter = contenido_Dos != null ?
                new ObjectParameter("Contenido_Dos", contenido_Dos) :
                new ObjectParameter("Contenido_Dos", typeof(string));
    
            var contenido_TresParameter = contenido_Tres != null ?
                new ObjectParameter("Contenido_Tres", contenido_Tres) :
                new ObjectParameter("Contenido_Tres", typeof(string));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var linkParameter = link != null ?
                new ObjectParameter("Link", link) :
                new ObjectParameter("Link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_CONTENIDOFRONT", idContenidoFrontParameter, idFrontParameter, tituloParameter, descripcionParameter, contenido_UnoParameter, contenido_DosParameter, contenido_TresParameter, idImagenParameter, linkParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_CONTENIDOSLIDE(Nullable<int> idContenidoSlide, Nullable<int> idSlide, string titulo, string descripcion, string contenido_Uno, string contenido_Dos, string contenido_Tres, Nullable<int> idImagen, string link)
        {
            var idContenidoSlideParameter = idContenidoSlide.HasValue ?
                new ObjectParameter("IdContenidoSlide", idContenidoSlide) :
                new ObjectParameter("IdContenidoSlide", typeof(int));
    
            var idSlideParameter = idSlide.HasValue ?
                new ObjectParameter("IdSlide", idSlide) :
                new ObjectParameter("IdSlide", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var contenido_UnoParameter = contenido_Uno != null ?
                new ObjectParameter("Contenido_Uno", contenido_Uno) :
                new ObjectParameter("Contenido_Uno", typeof(string));
    
            var contenido_DosParameter = contenido_Dos != null ?
                new ObjectParameter("Contenido_Dos", contenido_Dos) :
                new ObjectParameter("Contenido_Dos", typeof(string));
    
            var contenido_TresParameter = contenido_Tres != null ?
                new ObjectParameter("Contenido_Tres", contenido_Tres) :
                new ObjectParameter("Contenido_Tres", typeof(string));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var linkParameter = link != null ?
                new ObjectParameter("Link", link) :
                new ObjectParameter("Link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_CONTENIDOSLIDE", idContenidoSlideParameter, idSlideParameter, tituloParameter, descripcionParameter, contenido_UnoParameter, contenido_DosParameter, contenido_TresParameter, idImagenParameter, linkParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_FRONT(Nullable<int> idFront, Nullable<int> idModulo, string titulo, string descripcion)
        {
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_FRONT", idFrontParameter, idModuloParameter, tituloParameter, descripcionParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_FRONT_IMAGENES(Nullable<int> idFrontImagenes, Nullable<int> idFront, Nullable<int> idImagen)
        {
            var idFrontImagenesParameter = idFrontImagenes.HasValue ?
                new ObjectParameter("IdFrontImagenes", idFrontImagenes) :
                new ObjectParameter("IdFrontImagenes", typeof(int));
    
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_FRONT_IMAGENES", idFrontImagenesParameter, idFrontParameter, idImagenParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_SLIDE(Nullable<int> idSlide, Nullable<int> idFront, Nullable<int> idImagen, string titulo, string descripcion, string contenido_Uno, string contenido_Dos, string contenido_Tres, string link)
        {
            var idSlideParameter = idSlide.HasValue ?
                new ObjectParameter("IdSlide", idSlide) :
                new ObjectParameter("IdSlide", typeof(int));
    
            var idFrontParameter = idFront.HasValue ?
                new ObjectParameter("IdFront", idFront) :
                new ObjectParameter("IdFront", typeof(int));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var contenido_UnoParameter = contenido_Uno != null ?
                new ObjectParameter("Contenido_Uno", contenido_Uno) :
                new ObjectParameter("Contenido_Uno", typeof(string));
    
            var contenido_DosParameter = contenido_Dos != null ?
                new ObjectParameter("Contenido_Dos", contenido_Dos) :
                new ObjectParameter("Contenido_Dos", typeof(string));
    
            var contenido_TresParameter = contenido_Tres != null ?
                new ObjectParameter("Contenido_Tres", contenido_Tres) :
                new ObjectParameter("Contenido_Tres", typeof(string));
    
            var linkParameter = link != null ?
                new ObjectParameter("Link", link) :
                new ObjectParameter("Link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_SLIDE", idSlideParameter, idFrontParameter, idImagenParameter, tituloParameter, descripcionParameter, contenido_UnoParameter, contenido_DosParameter, contenido_TresParameter, linkParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_TRABAJA_CON_NOSOTROS(string nombres, string apellidos, string telefonoFijo, string celular, string archivoHojaDeVida)
        {
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var telefonoFijoParameter = telefonoFijo != null ?
                new ObjectParameter("TelefonoFijo", telefonoFijo) :
                new ObjectParameter("TelefonoFijo", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("Celular", celular) :
                new ObjectParameter("Celular", typeof(string));
    
            var archivoHojaDeVidaParameter = archivoHojaDeVida != null ?
                new ObjectParameter("ArchivoHojaDeVida", archivoHojaDeVida) :
                new ObjectParameter("ArchivoHojaDeVida", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_TRABAJA_CON_NOSOTROS", nombresParameter, apellidosParameter, telefonoFijoParameter, celularParameter, archivoHojaDeVidaParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_TRABAJA_CON_NOSOTROS(Nullable<decimal> idTrabajaConNosotros)
        {
            var idTrabajaConNosotrosParameter = idTrabajaConNosotros.HasValue ?
                new ObjectParameter("IdTrabajaConNosotros", idTrabajaConNosotros) :
                new ObjectParameter("IdTrabajaConNosotros", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_TRABAJA_CON_NOSOTROS", idTrabajaConNosotrosParameter);
        }
    
        public virtual ObjectResult<PA_INICIAR_SESION_Result> PA_INICIAR_SESION(string login, string clave)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_INICIAR_SESION_Result>("PA_INICIAR_SESION", loginParameter, claveParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_DOCUMENTO(string titulo, string archivo)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var archivoParameter = archivo != null ?
                new ObjectParameter("Archivo", archivo) :
                new ObjectParameter("Archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_DOCUMENTO", tituloParameter, archivoParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_DOCUMENTO(Nullable<int> idDocumento)
        {
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("IdDocumento", idDocumento) :
                new ObjectParameter("IdDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_DOCUMENTO", idDocumentoParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_DOCUMENTO(Nullable<int> idDocumento, string titulo)
        {
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("IdDocumento", idDocumento) :
                new ObjectParameter("IdDocumento", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_DOCUMENTO", idDocumentoParameter, tituloParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_USUARIO(string login, string clave)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_USUARIO", loginParameter, claveParameter);
        }
    
        public virtual int PA_DELETE_TBL_PORTAL_USUARIO(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_PORTAL_USUARIO", idUsuarioParameter);
        }
    
        public virtual int PA_DELETE_TBL_DIRECTORIO_INTERNO(Nullable<int> idDirectorioInterno)
        {
            var idDirectorioInternoParameter = idDirectorioInterno.HasValue ?
                new ObjectParameter("IdDirectorioInterno", idDirectorioInterno) :
                new ObjectParameter("IdDirectorioInterno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_DELETE_TBL_DIRECTORIO_INTERNO", idDirectorioInternoParameter);
        }
    
        public virtual int PA_INSERT_TBL_PORTAL_DIRECTORIO_INTERNO(string departamento, string extension, string email)
        {
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var extensionParameter = extension != null ?
                new ObjectParameter("Extension", extension) :
                new ObjectParameter("Extension", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERT_TBL_PORTAL_DIRECTORIO_INTERNO", departamentoParameter, extensionParameter, emailParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_DIRECTORIO_INTERNO(Nullable<int> idDirectorioInterno, string departamento, string extension, string email)
        {
            var idDirectorioInternoParameter = idDirectorioInterno.HasValue ?
                new ObjectParameter("IdDirectorioInterno", idDirectorioInterno) :
                new ObjectParameter("IdDirectorioInterno", typeof(int));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var extensionParameter = extension != null ?
                new ObjectParameter("Extension", extension) :
                new ObjectParameter("Extension", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_DIRECTORIO_INTERNO", idDirectorioInternoParameter, departamentoParameter, extensionParameter, emailParameter);
        }
    
        public virtual int PA_UPDATE_TBL_PORTAL_USUARIO(Nullable<int> idUsuario, string login, string clave)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_UPDATE_TBL_PORTAL_USUARIO", idUsuarioParameter, loginParameter, claveParameter);
        }
    }
}
