//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_SLIDE
    {
        public TBL_PORTAL_SLIDE()
        {
            this.TBL_PORTAL_CONTENIDOSLIDE = new HashSet<TBL_PORTAL_CONTENIDOSLIDE>();
        }
    
        public int IdSlide { get; set; }
        public int IdFront { get; set; }
        public int IdImagen { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual TBL_PORTAL_BIBLIOTECA_IMAGENES TBL_PORTAL_BIBLIOTECA_IMAGENES { get; set; }
        public virtual ICollection<TBL_PORTAL_CONTENIDOSLIDE> TBL_PORTAL_CONTENIDOSLIDE { get; set; }
        public virtual TBL_PORTAL_FRONT TBL_PORTAL_FRONT { get; set; }
    }
}
