//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_MODULO
    {
        public TBL_PORTAL_MODULO()
        {
            this.TBL_PORTAL_FRONT = new HashSet<TBL_PORTAL_FRONT>();
        }
    
        public int IdModulo { get; set; }
        public string NombreModulo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TBL_PORTAL_FRONT> TBL_PORTAL_FRONT { get; set; }
    }
}
