//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_MODULO
    {
        public TBL_PORTAL_MODULO()
        {
            this.TBL_PORTAL_FRONT = new HashSet<TBL_PORTAL_FRONT>();
        }
    
        public int IdModulo { get; set; }
        public string NombreModulo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TBL_PORTAL_FRONT> TBL_PORTAL_FRONT { get; set; }
    }
}
