//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_CONTENIDO
    {
        public decimal IdContenido { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public decimal IdImagen { get; set; }
        public decimal IdFront { get; set; }
        public string Tipo { get; set; }
    }
}
