//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_CONTENIDO_IMAGENES
    {
        public int IdContenidoImagen { get; set; }
        public int IdContenido { get; set; }
        public int IdImagen { get; set; }
    
        public virtual TBL_PORTAL_BIBLIOTECA_IMAGENES TBL_PORTAL_BIBLIOTECA_IMAGENES { get; set; }
        public virtual TBL_PORTAL_CONTENIDOFRONT TBL_PORTAL_CONTENIDOFRONT { get; set; }
    }
}
