//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_BIBLIOTECA_IMAGENES
    {
        public TBL_PORTAL_BIBLIOTECA_IMAGENES()
        {
            this.TBL_PORTAL_FRONT = new HashSet<TBL_PORTAL_FRONT>();
            this.TBL_PORTAL_SLIDE = new HashSet<TBL_PORTAL_SLIDE>();
        }
    
        public int IdImagen { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Path { get; set; }
        public Nullable<decimal> IdCategoriaBibliotecaImagenes { get; set; }
    
        public virtual ICollection<TBL_PORTAL_FRONT> TBL_PORTAL_FRONT { get; set; }
        public virtual ICollection<TBL_PORTAL_SLIDE> TBL_PORTAL_SLIDE { get; set; }
    }
}
