//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_CONTENIDO_IMAGENES
    {
        public int IdContenidoImagen { get; set; }
        public int IdContenido { get; set; }
        public int IdImagen { get; set; }
    
        public virtual TBL_PORTAL_BIBLIOTECA_IMAGENES TBL_PORTAL_BIBLIOTECA_IMAGENES { get; set; }
        public virtual TBL_PORTAL_CONTENIDOFRONT TBL_PORTAL_CONTENIDOFRONT { get; set; }
    }
}
