//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSSER.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PORTAL_CONTENIDOSLIDE
    {
        public int IdContenidoSlide { get; set; }
        public int IdSlide { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Contenido_Uno { get; set; }
        public string Contenido_Dos { get; set; }
        public string Contenido_Tres { get; set; }
        public int IdImagen { get; set; }
        public string Link { get; set; }
    
        public virtual TBL_PORTAL_SLIDE TBL_PORTAL_SLIDE { get; set; }
        public virtual TBL_PORTAL_BIBLIOTECA_IMAGENES TBL_PORTAL_BIBLIOTECA_IMAGENES { get; set; }
    }
}
